'use client';
import { Hero, About, Community, CTA, FeaturedCourses, FeaturedProgram, Testimonials } from "@/components/home";
import Navbar from "@/components/shared/Navbar";
import AuthProvider from "@/lib/context/AuthContext";

export default function Home() {
  return (
    <AuthProvider>
      <Navbar />
      <Hero />
      <About />
      <FeaturedProgram />
      <FeaturedCourses />
      <Testimonials />
      <Community />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
      <CTA />
    </AuthProvider>
  );
}
